core/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from core import views
from florencia import settings

app_name = 'core'
urlpatterns = [
    path('', views.SignInView.as_view(), name='sign_in'),
    # path('sign-up', views.SignUpView.as_view(), name='sign_up'),
    # path('recover-password', views.RecoverPasswordView.as_view(), name='recover_password'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('dashboard', views.DashboardView.as_view(), name='dashboard'),
    # path('profile', views.ProfileView.as_view(), name='profile'),
    path('redirect-session', views.redirect_session, name='redirect_session'),
    # path('list-competences/<int:id_test>/', views.get_competence_test, name='get_competence_test'),
]

florencia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('questions.urls')),
]

questions/urls.py
from django.urls import path

from questions import views

app_name = 'questions'
urlpatterns = [
    path('resolve/<slug:slug>/', views.QuestionResolve.as_view(), name='questions_resolve'),
    path('questions/', views.QuestionActions.as_view(), name='questions_box'),
    path('questions/<str:action>/', views.QuestionActions.as_view(), name='questions_add'),
    path('questions/<str:action>/<int:id>/', views.QuestionActions.as_view(), name='questions_action'),
]

core/models.py
from django.db import models

# Create your models here.

questions/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.urls import reverse


class ConfigModels(models.Model):
    """Contains default fields that could be included in future models"""
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.IntegerField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    updated_by = models.IntegerField(null=True, blank=True)

    class Meta:
        abstract = True


def validate_max_value_responses():
    return [MinValueValidator(0), MaxValueValidator(5)]


class QuestionBox(ConfigModels):
    title = models.CharField(verbose_name="Título del cuestionario", max_length=200)
    description = models.TextField(verbose_name="Descripción del cuestionario")
    active = models.BooleanField(verbose_name="Activar cuestionario?", default=False)
    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('questions:questions_resolve', kwargs={'slug': self.slug})


class QuestionList(ConfigModels):
    question_box = models.ForeignKey(
        QuestionBox, on_delete=models.CASCADE,
        related_name="questions_list"
    )
    question = models.TextField(verbose_name="Ingrese la pregunta a realizar")


class Option(models.Model):
    question = models.ForeignKey(
        QuestionList, on_delete=models.CASCADE,
        related_name="options"
    )
    option = models.TextField(verbose_name="Ingrese la descripción de la opción de respuesta")
    value = models.IntegerField(
        verbose_name="Ingrese el valor (de 0 a 5) de dicha opción",
        validators=validate_max_value_responses()
    )


class AnswersUser(ConfigModels):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def create(self, username, email, password):
        User.objects.create_user(username, email, password)

    class Meta:
        verbose_name_plural = 'Respuestas por usuarios'
        verbose_name = 'Respuesta de usuario'


class AnswerQuestionList(models.Model):
    user = models.ForeignKey(AnswersUser, on_delete=models.CASCADE)
    question = models.ForeignKey(
        QuestionList, on_delete=models.CASCADE,
        related_name="answers_questions"
    )
    answer = models.ForeignKey(
        Option, on_delete=models.CASCADE,
        related_name="option_answer_question"
    )

core/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from django.utils.translation import ugettext_lazy as _


def redirect_session(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('questions:questions_box'))

    return redirect(reverse_lazy('core:sign_in'))


class SignInView(View):
    template_name = "core/sign_in.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse_lazy('core:redirect_session'))
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email', None)
        password = request.POST.get('password', None)
        get_user = User.objects.filter(email__exact=email).first()
        if get_user:
            user = authenticate(request, username=get_user.username, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse_lazy('core:redirect_session'))
            else:
                messages.error(request, _('Correo o contraseña incorrecta. ¡Inténtelo de nuevo!'))
        else:
            messages.error(request, _('Correo o contraseña incorrecta. ¡Inténtelo de nuevo!'))
        return redirect(reverse_lazy('core:sign_in'))


class DashboardView(LoginRequiredMixin, View):
    template_name = "core/dashboard.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        pass

questions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views import View

from questions.question_controller import QuestionController
from questions.resolvers.question_actions import QuestionAction
from questions.resolvers.question_answers import QuestionAnswers


class QuestionActions(LoginRequiredMixin, View):
    template_name = "questions/questions_box.html"
    actions = ["add", "edit", "statistics", "delete_q", "delete_b"]

    def get(self, request, *args, **kwargs):
        action = kwargs.get("action")
        if action in self.actions:
            file = action.replace("_q", "")
            file = file.replace("_b", "")
            self.template_name = f"questions/questions_{file}.html"

        if kwargs.get("id"):
            if action == "delete_q":
                context = QuestionController.get_data_question_list(
                    kwargs.get("id")
                )
            elif action == "delete_b":
                context = QuestionController.get_data_question_box(
                    kwargs.get("id")
                )
            else:
                context = QuestionController.get_data_question_edit(kwargs.get("id"))

                if action == "statistics":
                    QuestionController.get_statistics(context)
        else:
            context = QuestionController.get_questions_box()

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        return QuestionAction.resolve(request, **kwargs)


class QuestionResolve(View):
    def get(self, request, *args, **kwargs):
        return QuestionAnswers.resolve(request, 'get', **kwargs)

    def post(self, request, *args, **kwargs):
        return QuestionAnswers.resolve(request, 'post', **kwargs)

core/templates/core/dashboard.html
{% extends 'base.html' %}
{% load static i18n %}
{% block header_text %}
    {% trans 'Dashboard' %}
{% endblock header_text %}


{% block extra_css %}
{% endblock %}

{% block content %}
    <a href="{% url 'questions:questions_box' %}">Questions</a>

    <a href="{% url 'core:logout' %}">
        Logout
    </a>
    <h1>Dashboard</h1>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

core/templates/core/sidebar.html
<div class="sidebar-left">
    <div class="logo">{{ request.user.username }}</div>
    <div class="action-sidebar">
        <ul class="menu">
            <li>
                <i class="material-icons">work_outline</i>
                <a class="text" href="{% url 'questions:questions_box' %}">Forms</a>
            </li>
        </ul>

        <ul class="menu">
            <li>
                <i class="material-icons">logout</i>
                <a class="text" href="{% url 'core:logout' %}">Cerrar Sesión</a>
            </li>
        </ul>
    </div>
</div>

core/templates/core/sign_in.html
{% extends 'base.html' %}
{% load static i18n %}


{% block extra_css %}
    <style>
        .main {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            width: 400px !important;
            height: auto !important;
        }

        .action-form {
            margin-top: 5px !important;
            justify-content: center !important;
            margin-bottom: 20px !important;
        }

        .action-form .button {
            width: 100%;
        }

        .col.field, .col.alert-item {
            padding-top: 0 !important;
            padding-bottom: 0 !important;
            margin: 0!important;
        }

        .title-group-field {
            font-size: 2rem;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
            margin-top: 20px !important;
        }
    </style>
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}
    <div class="main">
        <form action="" method="post" name="login">
            {% csrf_token %}
            <div class="row">
                <div class="title-group-field"><b>Iniciar Sesión</b></div>
                {% for message in messages %}
                    <div class="col s12 alert-item">
                        <div class="alert {{ message.tags }}" role="alert">
                            <div class="text">{{ message }}</div>
                            <button type="button" class="close"></button>
                        </div>
                    </div>
                {% endfor %}
                <div class="col field s12 m12">
                    <div class="j-field outlined">
                        <input class="input-field" type="email" id="email" name="email" autocomplete="off"
                               required="required" maxlength="200"/>
                        <label for="title">Correo Electrónico</label>
                        <div class="helper-field"></div>
                    </div>
                </div>
                <div class="col field s12 m12">
                    <div class="j-field outlined">
                        <input class="input-field" type="password" id="password" name="password"
                               autocomplete="off"
                               required="required"/>
                        <label for="description">Contraseña</label>
                        <div class="helper-field"></div>
                    </div>
                </div>
                <div class="col s12 action-form">
                    <button type="submit" class="button primary">Iniciar sesión</button>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}


<div class="container login-container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div id="first">
                <div class="myform form">
                    <div class="logo mb-3">
                        <div class="col-md-12 text-center">
                            <h1>{% trans 'Login' %}</h1>
                        </div>
                    </div>
                    <form action="" method="post" name="login">
                        {% csrf_token %}
                        {% for message in messages %}
                            <div class="alert {{ message.tags }}" role="alert">{{ message }}</div>
                        {% endfor %}
                        <div class="form-group">
                            <label for="email">{% trans 'Email' %}</label>
                            <input type="email" name="email" class="form-control" id="email"
                                   aria-describedby="emailHelp" placeholder="{% trans 'Enter email' %}">
                        </div>
                        <div class="form-group">
                            <label for="password">{% trans 'Password' %}</label>
                            <input type="password" name="password" id="password" class="form-control"
                                   aria-describedby="emailHelp" placeholder="{% trans 'Enter password' %}">
                        </div>
                        <div class="col-md-12 text-center ">
                            <button type="submit"
                                    class=" btn btn-block mybtn btn-u tx-tfm">{% trans 'Login' %}</button>
                        </div>
                        <div class="col-md-12 ">
                            <div class="login-or">
                                <hr class="hr-or">
                                <span class="span-or">{% trans 'or' %}</span>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

questions/templates/questions/questions_404.html
{% extends 'base.html' %}
{% load static i18n %}


{% block extra_css %}
    <style>
    .main {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    .title {
        font-size: 8rem;
        font-weight: bold;
    }
    </style>
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}
    <div class="main">
        <div class="title">404</div>
        <div class="extra">
            Parece que no hemos encontrado tu formulario, contacta con tu administrador
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

questions/templates/questions/questions_box.html
{% extends 'base.html' %}
{% load static i18n questions_tags %}


{% block extra_css %}
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}

    <div class="main">
        {% include "core/sidebar.html" %}
        <div class="content">
            <div class="app">
                <div class="head actions">
                    <div>
                        <div class="title">Formularios</div>
                        <div class="description">Consulte acá tus formularios creados</div>
                    </div>
                    <div>
                        <a type="button"
                           class="button primary right"
                           href="{% url 'questions:questions_add' action="add" %}">
                            Crear formulario
                        </a>
                    </div>
                </div>
                <div class="form row list-questions">
                    <div class="row">
                        {% for message in messages %}
                            <div class="col s12 alert {{ message.tags }}" role="alert">
                                <div class="text">{{ message }}</div>
                                <button type="button" class="close"></button>
                            </div>
                        {% endfor %}
                    </div>
                    <table class="col s12" style="width: 100%; text-align: left">
                        <thead>
                        <tr>
                            <th style="width: 50%">Titulo</th>
                            <th>¿Activo?</th>
                            <th>Preguntas</th>
                            <th>Respuestas</th>
                            <th>Acciones</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for question in questions %}
                            <tr>
                                <td>{{ question.title }}</td>
                                <td>
                                    <form action="{% url 'questions:questions_action' action='active' id=question.id %}"
                                          method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="button inert">
                                            {% if question.active %}
                                                <i class="material-icons outlined">check_box</i>
                                            {% else %}
                                                <i class="material-icons outlined">check_box_outline_blank</i>
                                            {% endif %}
                                        </button>
                                    </form>
                                </td>
                                <td>{{ question|counter_questions }}</td>
                                <td>{{ question.id|counter_answers }}</td>
                                <td>
                                    <a class="button" title="Ver Estadísticas"
                                       href="{% url 'questions:questions_action' action='statistics' id=question.id %}">
                                        <i class="material-icons">visibility</i>
                                    </a>
                                    <a class="button" title="Editar"
                                       href="{% url 'questions:questions_action' action="edit" id=question.id %}"
                                    >
                                        <i class="material-icons">edit</i>
                                    </a>
                                    <a class="button" title="Eliminar"
                                       href="{% url 'questions:questions_action' action="delete_b" id=question.id %}"
                                    >
                                        <i class="material-icons">delete</i>
                                    </a>
                                    <a class="button copy-data" id="copy-{{ forloop.counter }}" title="Compartir"
                                       data-clipboard-text="{{ request.META.HTTP_HOST }}{{ question.get_absolute_url }}"
                                    >
                                        <i class="material-icons">share</i>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

questions/templates/questions/questions_delete.html
{% extends 'base.html' %}
{% load static i18n %}


{% block extra_css %}
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}

    <div class="main">
        {% include "core/sidebar.html" %}
        <div class="content">
            <div class="app" style="display: flex; align-items: center">
                <form method="post">
                    <div class="info row center">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ id }}">
                        <div class="title-group-field"><b>Estás seguro de querer eliminar:</b></div>
                        <div class="head" style="padding: 0">
                            <div class="title">{{ title }}</div>
                        </div>
                        <div class="col s12">
                            <a type="button"
                               class="button danger"
                               href="{% url 'questions:questions_action' action='edit' id=id_edit %}">
                                Cancelar
                            </a>
                            <button type="submit"
                                    class="button primary">
                                Si, eliminar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}
{% endblock extra_js %}

questions/templates/questions/questions_resolve.html
{% extends 'base.html' %}
{% load static i18n questions_tags %}


{% block extra_css %}
    <style>
        form {
            width: 100%;
        }
    </style>
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name="id_question" value="{{ question.id }}">
        <input type="hidden" name="question_count" value="{{ questions_list_count }}">
        <div class="main">
            <div class="app">
                <div class="head">
                    <div>
                        <div class="title">{{ question.title }}</div>
                        <div class="description">{{ question.description }}</div>
                    </div>
                </div>

                <div class="row">
                    {% for message in messages %}
                        <div class="col s12">
                            <div class="alert {{ message.tags }}">
                                <div class="text">{{ message }}</div>
                                <button type="button" class="close"></button>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="form">
                    <div class="row">
                        {% for q in questions_list %}
                            <div class="div col s12 content-questions-resolve">
                                <h2 class="title-question">{{ q.question }}</h2>
                                <input type="hidden" name="id_question_{{ forloop.counter }}"
                                       value="{{ q.id }}">
                                <div class="row">
                                    <div class="col s12">
                                        {% aux_parent_account forloop.counter as q_count %}
                                        {% options_question q as options %}

                                        <ul>
                                            {% for option in options %}
                                                <li>
                                                    <input type="radio"
                                                           id="option_{{ forloop.counter0 }}_question_{{ q_count }}"
                                                           name="option_question_{{ q_count }}"
                                                           value="{{ option.id }}">
                                                    <label for="option_{{ forloop.counter0 }}_question_{{ q_count }}">
                                                        {{ option.option }}
                                                    </label>

                                                    <div class="check"></div>
                                                </li>
                                            {% endfor %}
                                        </ul>

                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

                <div class="row">

                    <div class="col s12 action-form">
                        <button type="submit" class="button primary">Guardar formulario</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock content %}

{% block extra_js %}
    <script>
        function resizeForm() {
            let el = document.getElementsByTagName("li")
            for (let i = 0; i < el.length; i++) {
                let e = el[i];
                let height = e.scrollHeight
                e.style.height = `${height}px`;
            }
        }

        window.addEventListener("resize", resizeForm, false);
        window.onload = resizeForm;
        // window.onresize = resizeForm;
    </script>
{% endblock extra_js %}

questions/templates/questions/questions_statistics.html
{% extends 'base.html' %}
{% load static i18n %}


{% block extra_css %}
{% endblock %}

{% block class_body %}dashboard{% endblock class_body %}

{% block content %}

    <div class="main">
        {% include "core/sidebar.html" %}
        <div class="content">
            <div class="app">
                <div class="head actions">
                    <div>
                        <div class="title">{{ question.title }}</div>
                        <div class="description">{{ question.description }}</div>
                    </div>
                    <div>
                        <a type="button"
                           class="button right"
                           href="{% url 'questions:questions_box' %}">
                            Volver
                        </a>
                        <a type="button"
                           class="button primary right"
                           href="{% url 'questions:questions_action' action="edit" id=question.id %}">
                            Editar formulario
                        </a>
                        <a class="button copy-data" id="copy-{{ forloop.counter }}" title="Compartir"
                           style="padding: 14px"
                           data-clipboard-text="{{ request.META.HTTP_HOST }}{{ question.get_absolute_url }}"
                        >
                            <i class="material-icons">share</i>
                        </a>
                    </div>
                </div>
                <div class="info row">
                    <div class="col s12 m4">
                        <div class="score">
                            <div class="total">{{ average }}</div>
                            <div class="description">Resultado total</div>
                        </div>
                    </div>
                    {% for v in data_q %}
                        <div class="col s12 m6">
                            <div id="data-char-{{ forloop.counter }}"></div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_js %}

    <script src="https://code.highcharts.com/highcharts.src.js"></script>

    <script>
        // Chars by question
        {% for key, value in data_q.items %}
            Highcharts.chart('data-char-{{ forloop.counter }}', {
                chart: {
                    type: 'column'
                },
                title: {
                    text: 'Estadísticas para: {{ key }}'
                },
                subtitle: {
                    text: ''
                },
                accessibility: {
                    announceNewData: {
                        enabled: true
                    }
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'Total # de respuestas por opción'
                    }

                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    series: {
                        borderWidth: 0,
                        dataLabels: {
                            enabled: true,
                            format: '{point.y:.0f}'
                        }
                    }
                },

                tooltip: {
                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
                    pointFormat: '<b>{point.y:.0f}</b> personas han respondido: <br> <i>{point.name}</i><br/>'
                },

                series: [
                    {
                        name: "Calificación",
                        colorByPoint: true,
                        data: [
                            {% for key, data in value.items %}
                                {
                                    name: "{{ data.description }}",
                                    y: {{ data.value }},
                                },
                            {% endfor %}
                        ]
                    }
                ],
            });
        {% endfor %}

    </script>

{% endblock extra_js %}

templates/base.html
{% load static sass_tags %}
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="es" class="ie8"> <![endif]-->
<!--[if IE 9]>
<html lang="es" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es"> <!--<![endif]-->
<head>
    <title>Florencia</title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="Shortcut icon">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    <link rel="stylesheet" href="{% sass_src 'css/style.scss' %}">

    {% block extra_css %}
    {% endblock extra_css %}

</head>

<body class="{% block class_body %}{% endblock class_body %}">

<div id="alerts"></div>

{% block content %}{% endblock content %}


<script src="{% static 'js/libs/clipboard.min.js' %}"></script>
<script src="{% static 'js/j-ui.js' %}"></script>
{% block extra_js %}
{% endblock extra_js %}

</body>
</html>